version: '3.8'

services:
  mining_worker:
    build: .
    image: phls2_mining-mergetools:latest
    container_name: phls2_mining-mergetools

    volumes:
      - ./input:/usr/src/miningframework/input
      - ./dependencies:/usr/src/miningframework/dependencies
      - ./mergeAnalysisOutput:/usr/src/miningframework/mergeAnalysisOutput
      - ./clonedRepositories:/usr/src/miningframework/clonedRepositories
      - ./output:/usr/src/miningframework/output

    command: 
      [
        "-i", "injectors.SampleCollectionModule",
        "-t", "1", 
        "-e", ".rs",
        "-r", "42",
        "-m", "1",
        "input/mergeTools/rs.csv",
        "mergeAnalysisOutput"
      ]

    restart: "no"
