version: '3.8'

services:
  mining_worker:
    build: .
    image: mining-framework:latest
    container_name: mining-framework

    volumes:
      - ./input:/usr/src/miningframework/input
      - ./dependencies:/usr/src/miningframework/dependencies
      - ./mergeAnalysisOutput:/usr/src/miningframework/mergeAnalysisOutput
      - ./clonedRepositories:/usr/src/miningframework/clonedRepositories
      - ./output:/usr/src/miningframework/output

    command: 
      [
        "-i", "injectors.MergirafSemiModule",
        "-t", "4", 
        "-k",
        "-r", "42",
        "-m", "200",
        "input/topProjectsJava.csv",
        "mergeAnalysisOutput"
      ]

    restart: "no"
